### ISSUE TITLE
Major performance hit and slowdown.

### ISSUE THREAD

**Issue by ghost** [Sirius902/LuaBackend#1]
Upon using this version of luabackend, a number of samples report the game dropping a lot of FPS or the game slowing down entirely.

**Comment by Sirius902** [comment]
After some investigation, I think we've found that a possible culprit could be the save png actually. Several have reported that deleting their `KHIIFM.png` and letting the game regenerate a blank one has fixed the issue for them. Are you experiencing the issue personally? If so, does (probably best to make a backup first) deleting the save file fix the issue?

**Comment by ghost** [comment]
A few days after the issue was posted, the problem seems to have fixed itself based on later playthroughs. I'll be sure to suggest this to other users with the same problem. Thank you!

**Comment by Sirius902** [comment]
No problem. If the issue seems to come back and the save png doesn't fix the problem then feel free to reopen the issue.
