### ISSUE TITLE
Not working on Steam Deck (Steam Version)

### ISSUE THREAD

**Issue by HydroSulphide** [Sirius902/LuaBackend#15]
I tried getting my lua scripts, that work on windows, to run on steam deck. This is what I did, maybe I'm missing a step or did use wrong paths:

* Download LuaBackend hook and copied DBGHELP.dll, lua54.dll and LuaBackend.toml to the directory where "KINGDOM HEARTS FINAL MIX.exe" is located
* Renamed "DBGHELP.dll" to "dinput8.dll"
* Made sure the kh1 section in the LuaBackend.toml looks like this (base = 0x0 is correct for the mods I'm using, path was changed to same folder like on windows, but inside the prefix as absolute path):
```
[kh1]
scripts = [{ path = "/home/deck/.local/share/steamapps/compatdata/2552430/pfx/drive_c/users/steamuser/Documents/My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX/scripts/kh1/", relative = false }]
base = 0x0
thread_struct = 0x22BAA20
exe = "KINGDOM HEARTS FINAL MIX.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
```
* Added the following to Properties->General->Launch Options in the properties of the Kingdom Hearts 1.5+2.5 library entry in steam to override the native dinput8.dll with the one from LuaBackend: ```WINEDLLOVERRIDES="dinput8=n,b" %command%```

After all these steps the game launches like normal, but no scripts are active and the lua console doesn't open by pressing F2.

**Comment by spongebob902** [comment]
I'm having the same trouble

**Comment by HydroSulphide** [comment]
I was stupid and had the old thread struct address still in my LuaBackend.toml. I got it working and this is my updated step-by-step guide. Maybe it will help someone who finds it:

* Download LuaBackend hook and make sure your LuaBackend.toml looks like this:
```
[kh1]
scripts = [{ path = "scripts/kh1/", relative = true }]
base = 0x0
thread_struct = 0x22BAA20
exe = "KINGDOM HEARTS FINAL MIX.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
[kh2]
scripts = [{ path = "scripts/kh2/", relative = true }]
base = 0x0
thread_struct = 0x8A0930
exe = "KINGDOM HEARTS II FINAL MIX.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
[bbs]
scripts = [{ path = "scripts/bbs/", relative = true }]
base = 0x0
thread_struct = 0x110B84A0
exe = "KINGDOM HEARTS Birth by Sleep FINAL MIX.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
[recom]
scripts = [{ path = "scripts/recom/", relative = true }]
base = 0x0
thread_struct = 0xC072C0
exe = "KINGDOM HEARTS Re_Chain of Memories.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
[kh3d]
scripts = [{ path = "scripts/kh3d/", relative = true }]
base = 0x0
thread_struct = 0x14DA6F20
exe = "KINGDOM HEARTS Dream Drop Distance.exe"
game_docs = "My Games/KINGDOM HEARTS HD 2.8 Final Chapter Prologue"
```
* Rename DBGHELP.dll to dinput8.dll
* Copy "dinput8.dll", "lua54.dll" and "LuaBackend.toml" in the same directory as "KINGDOM HEARTS FINAL MIX.exe" (default location: "/home/deck/.local/Steam/steamapps/common/KINGDOM HEARTS -HD 1.5+2.5 ReMIX-")
* Navigate to the "/Documents/My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX" directory of the KINGDOM HEARTS HD 1.5+2.5 ReMIX proton prefix: (default location: "/home/deck/.local/share/Steam/steamapps/compatdata/2552430/pfx_drive/users/steamuser/Documents/My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX")
* Inside this folder create a directory "scripts" and inside that directory create a directory called "kh1"
* Place your scripts inside this directory (default location: "/home/deck/.local/share/Steam/steamapps/compatdata/2552430/pfx_drive/users/steamuser/Documents/My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX/scripts/kh1")
* Open steam and navigate to "KINGDOM HEARTS -HD 1.5+2.5 ReMIX-" in your library and set following launch options (found in settings->properties->general->launch options): ```WINEDLLOVERRIDES="dinput8=n,b" %command%```
This step is needed so that our dinput8.dll we copied before is used instead of the native one installed in the proton prefix


Edit:
If you don't want to navigate to the scripts folder inside the prefix every time you install a script, you can define a custom path inside the LuaBackend.toml, that is not relative to the Documents folder inside the prefix. For example:
```
[kh1]
scripts = [{ path = "/home/deck/Documents/KINGDOM HEARTS HD 1.5+2.5 ReMIX/scripts/kh1/", relative = false }]
base = 0x0
thread_struct = 0x22BAA20
exe = "KINGDOM HEARTS FINAL MIX.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
```

**Comment by KingNagito** [comment]
Hey I still can't get it to work and I followed your instructions precisely. I'm trying to install some lua scripts for bbs, but none of them seem to be working when I'm opening the game. Any ideas about what I'm missing?

**Comment by cll0ud** [comment]
I got it working on my Steam Deck following these instructions, for the Steam release, for KH1 at least. 
However I've had a couple non-critical issues:

- I can open the console with F2 but it's completely empty, nothing shows up
- The suggestion to have the scripts outside the proton prefix didn't work at all. I always get the message that the path wasn't found. Tried exactly as the example above and nothing. I reverted back to the relative path and pasted my scripts inside the prefix and only then I got it working.

**Comment by HydroSulphide** [comment]
Regarding the empty console: I opened another [github issue](https://github.com/Sirius902/LuaBackend/issues/16) describing the problem. I didn't find a solution, but also didn't try that hard, because as long as it works the output is not that important for me personally, but I would appreciate if anyone finds a solution. Some people told me that they see output on steam deck after using my guide. I don't know what's causing the issue for some people including me.

What exactly is the message you are getting and where is this error message printed? That's interesting, but I don't really know what the problem could be. Should be just a typo maybe or you forgot to set relative to false or something like that. It should work just like I wrote it. My scripts are only at "/home/deck/Documents/KINGDOM HEARTS HD 1.5+2.5 ReMIX/scripts/kh1/" and not in the prefix folder and it did just work for me.

**Comment by cll0ud** [comment]
Happens as soon as I open KH1. I took a screenshot:
![Screenshot_20240706_085823](https://github.com/Sirius902/LuaBackend/assets/2008155/698095fa-2f4c-4fd2-915b-1d9bba6873f2)
It works if I move it back to the proton prefix folder. It's really not a major issue for me tho, I just created a shortcut for the prefix folder on my desktop to make it easier to manage scripts.
That said, I'm currently only using some simple and light scripts, would be nice to be able to move these to the external SD in case I was going to use texture packs and other heavier stuff as I have the 64gb internal memory model.

**Comment by HydroSulphide** [comment]
That's really weird. Should definitely work like this. But you shouldn't be worried about space regarding Lua scripts. They are just scripts and will never be too big. Things like texture packs are patches that change the exe and the game files inside the game directory. I don't know if it's possible to put these on the SD card without installing the game on the SD card in the first place. Maybe with sym links, but I didn't test it.

**Comment by cll0ud** [comment]
Oh, I see. It's my first time messing with mods for these games, so I didn't know textures and the likes are directly patched in the executables. I should be fine then, I already got the games installed in the SD card.
Thanks for all the help!

**Comment by rowleyfan3620** [comment]
> I was stupid and had the old thread struct address still in my LuaBackend.toml. I got it working and this is my updated step-by-step guide. Maybe it will help someone who finds it:
> 
> * Download LuaBackend hook and make sure your LuaBackend.toml looks like this:
> 
> ```
> [kh1]
> scripts = [{ path = "scripts/kh1/", relative = true }]
> base = 0x0
> thread_struct = 0x22BAA20
> exe = "KINGDOM HEARTS FINAL MIX.exe"
> game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
> [kh2]
> scripts = [{ path = "scripts/kh2/", relative = true }]
> base = 0x0
> thread_struct = 0x8A0930
> exe = "KINGDOM HEARTS II FINAL MIX.exe"
> game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
> [bbs]
> scripts = [{ path = "scripts/bbs/", relative = true }]
> base = 0x0
> thread_struct = 0x110B84A0
> exe = "KINGDOM HEARTS Birth by Sleep FINAL MIX.exe"
> game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
> [recom]
> scripts = [{ path = "scripts/recom/", relative = true }]
> base = 0x0
> thread_struct = 0xC072C0
> exe = "KINGDOM HEARTS Re_Chain of Memories.exe"
> game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
> [kh3d]
> scripts = [{ path = "scripts/kh3d/", relative = true }]
> base = 0x0
> thread_struct = 0x14DA6F20
> exe = "KINGDOM HEARTS Dream Drop Distance.exe"
> game_docs = "My Games/KINGDOM HEARTS HD 2.8 Final Chapter Prologue"
> ```
> 
> * Rename DBGHELP.dll to dinput8.dll
> * Copy "dinput8.dll", "lua54.dll" and "LuaBackend.toml" in the same directory as "KINGDOM HEARTS FINAL MIX.exe" (default location: "/home/deck/.local/Steam/steamapps/common/KINGDOM HEARTS -HD 1.5+2.5 ReMIX-")
> * Navigate to the "/Documents/My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX" directory of the KINGDOM HEARTS HD 1.5+2.5 ReMIX proton prefix: (default location: "/home/deck/.local/share/Steam/steamapps/compatdata/2552430/pfx_drive/users/steamuser/Documents/My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX")
> * Inside this folder create a directory "scripts" and inside that directory create a directory called "kh1"
> * Place your scripts inside this directory (default location: "/home/deck/.local/share/Steam/steamapps/compatdata/2552430/pfx_drive/users/steamuser/Documents/My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX/scripts/kh1")
> * Open steam and navigate to "KINGDOM HEARTS -HD 1.5+2.5 ReMIX-" in your library and set following launch options (found in settings->properties->general->launch options): `WINEDLLOVERRIDES="dinput8=n,b" %command%`
>   This step is needed so that our dinput8.dll we copied before is used instead of the native one installed in the proton prefix
> 
> Edit: If you don't want to navigate to the scripts folder inside the prefix every time you install a script, you can define a custom path inside the LuaBackend.toml, that is not relative to the Documents folder inside the prefix. For example:
> 
> ```
> [kh1]
> scripts = [{ path = "/home/deck/Documents/KINGDOM HEARTS HD 1.5+2.5 ReMIX/scripts/kh1/", relative = false }]
> base = 0x0
> thread_struct = 0x22BAA20
> exe = "KINGDOM HEARTS FINAL MIX.exe"
> game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"
> ```

Just wanting to drop a note here saying that these instructions worked for me, 2025-02-18. Thanks so much for your help! I was banging my head against the wall.
