### ISSUE TITLE
.dll file borks controller input

### ISSUE THREAD

**Issue by thenerdy0ne** [Sirius902/LuaBackend#2]
Morning, I've been struggling with identifying the reason for my controller no longer working over steam link and finally figured out that the issue resolves if i rename the .dll so it's not usable. Not sure if this is known, or intended behavior but if possible it'd be lovely to have steam input support back for this game. Please let me know if you need anymore information.

**Comment by PoochieMix** [comment]
Having the same issue. Happens with or without any scripts installed. Still recognizes 360 controllers if using DS4Windows and launching EGS directly.

**Comment by FeshPince** [comment]
Yep, this is the issue I was going to come here and post before seeing this. I'm the user who DM'd you on discord, Sirius, who you told to make an issue if all else fails. This is the _exact_ issue I'm experiencing. LuaBackend launches and works great with all working scripts, but my PS5 controller, used through Steam, is completely ignored by the game if the .dll is in my directory for KHHD.

**Comment by Sirius902** [comment]
Hello all, I suspect steam input does something dubious with the `DINPUT8.dll` to get input to work and is instead interacting with the backend's `dll` causing it to fail. I did try to instead replace `DBGHELP.dll` as an experiment and you can find it [here](https://github.com/Sirius902/LuaBackend/suites/4379822712/artifacts/115306728). Please try it out and let me know if it works and I'll merge it into the main branch. You will need to remove the `DINPUT8.dll` you have in the game folder and instead place this `DBGHELP.dll` in there instead.

**Comment by FeshPince** [comment]
> Hello all, I suspect steam input does something dubious with the `DINPUT8.dll` to get input to work and is instead interacting with the backend's `dll` causing it to fail. I did try to instead replace `DBGHELP.dll` as an experiment and you can find it [here](https://github.com/Sirius902/LuaBackend/suites/4379822712/artifacts/115306728). Please try it out and let me know if it works and I'll merge it into the main branch. You will need to remove the `DINPUT8.dll` you have in the game folder and instead place this `DBGHELP.dll` in there instead.

This file seems to have completely fixed the issue on my end. I hope the same is true for anyone else experiencing this!

**Comment by thenerdy0ne** [comment]
Confirming as well that the fix works for me as well. I'm officially naming my first child Sirius902.

**Comment by Sirius902** [comment]
Closed via 56930e89eb98399c446b9b67fc470d10c7be2c2e.
