### ISSUE TITLE
KH1 crashing

### ISSUE THREAD

**Issue by SebaHelmo** [Sirius902/LuaBackend#3]
Hello, I'm trying to play kh1 using "Rich precense" but does not work. It crash every time I opened kh1. 
I have "DINPUT8.dll" in KH_1.5_2.5 and the scripts in "Documents\KINGDOM HEARTS HD 1.5+2.5 ReMIX\scripts\kh1".
I try reinstalling the game, change the folder to another HDD but nothing :c

**Comment by Sirius902** [comment]
Do you mean [this mod](https://www.nexusmods.com/kingdomheartsfinalmix/mods/1)? If so I will try it out and see if it crashes for me. If I can't replicate it I would need you to find where the game crashes with Windbg and I could give you steps on how to do that.

**Comment by Sirius902** [comment]
Using the above script the rich presence worked and I could not replicate a crash myself, but if you want to try and help debug the crash you can:
* Download [Windbg Preview](https://www.microsoft.com/store/productId/9PGJGD53TN86) from the Microsoft Store.
* Open Windbg and open Kingdom Hearts I.5 + II.5 to the game select screen.
* Press F6 and look for and double click on `KINGDOM HEARTS I.5 + II.5 ReMIX.exe`.
* In the console on the middle left type `.childdbg 1` and press enter and then also do the same for `g`.
* Now launch KINGDOM HEARTS FINAL MIX.
* In the console enter the following commands: `|0s`, `.childdbg 0`, `|1s`, `.childdbg 0`, `sxn bpe`, and `g`.
* The game should now run until it crashes, showing exactly where it crashed in the Command pane. After this happens, run `r` in the console.
* Click on the `Stack` tab on the bottom right.

If you can then send a screenshot of the Command pane and Stack pane I can try and figure out what's going wrong.

**Comment by Sirius902** [comment]
I think this may be the same as #4 so I'm going to close it for now in favor of tracking the issue in one place.
