### ISSUE TITLE
DBGHelp.dll Crashes KH1

### ISSUE THREAD

**Issue by hellshakeyan0** [Sirius902/LuaBackend#4]
Updated to the new release and can no longer launch the game.

**Comment by Sirius902** [comment]
Were you sure to remove the old `DINPUT8.dll`? Also what scripts are you using?

**Comment by hellshakeyan0** [comment]
yeah i tried it after full removal and was still getting crashes. Here are my kh1 scripts. Rolling back fixed the issue for now.
![image](https://user-images.githubusercontent.com/83040254/143153941-e7299598-0086-4715-b383-02bcecf42e41.png)

**Comment by Sirius902** [comment]
Alright. Are you able to follow the below steps?
* Download [Windbg Preview](https://www.microsoft.com/store/productId/9PGJGD53TN86) from the Microsoft Store.
* Open Windbg and open Kingdom Hearts I.5 + II.5 to the game select screen.
* Press F6 and look for and double click on `KINGDOM HEARTS I.5 + II.5 ReMIX.exe`.
* In the console on the middle left type `.childdbg 1` and press enter and then also do the same for `g`.
* Now launch KINGDOM HEARTS FINAL MIX.
* In the console enter the following commands: `|0s`, `.childdbg 0`, `|1s`, `.childdbg 0`, `sxn bpe`, and `g`.
* The game should now run until it crashes, showing exactly where it crashed in the Command pane. After this happens, run `r` in the console.
* Click on the `Stack` tab on the bottom right.
* Send a screenshot of the Command pane and Stack pane.

This will help me debug the crash.

**Comment by randoomdude** [comment]
I tried following your instructions cause I was having the same issue, but I'm not sure what you mean by console or commands on the middle left
![image](https://user-images.githubusercontent.com/6027132/146244813-8f3fd4b7-972c-494f-ba49-cc82da08a373.png)

**Comment by randoomdude** [comment]
Do you do this with DBGHelp.dll in the folder or no? Also whenever you double click KINGDOM HEARTS I.5 + II.5 ReMIX.exe in the Windbg preview it pauses (freezes?) the Kingdom Hearts ReMix launcher

**Comment by Sirius902** [comment]
@randoomdude Yes, you do it with the `DBGHelp.dll` in the folder. The program is supposed to freeze when you attach the debugger, you can only run commands when the program is paused. Running the `g` (go) command resumes the program. (Which you should only do after you've entered the commands to debug it properly).

~~Here is the console / command window from your picture.~~ Here is the console from your picture. In there you can type in commands and press enter to execute them. When I referred to the Command pane earlier I meant the space directly above it that has stuff like `ModLoad` on the left.
![markup](https://user-images.githubusercontent.com/10891979/146257209-b85c8e96-4b16-421e-a65a-695382d13f9c.png)

**Comment by Sirius902** [comment]
Are you still experiencing this issue? If not it should probably be closed.

**Comment by Sirius902** [comment]
Feel free to reopen if the issue still persists.
